
name: Build

on:
  push:
    # Always build when there are new commits to master
    branches:
      - master

    # Always build release-tags
    tags:
      - 'releases/**'

jobs:
  start-agents:
    name: "Start build agents"
    runs-on: ubuntu-latest
    steps:
      - run: curl ${{ secrets.WATCHDOG_TRIGGER_URL }}

  build-win64:
    name: "Build for Win64"

    runs-on: game_build_agent

    timeout-minutes: 120

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup credentials for cloud storage
        run: $env:GCP_GAME_BUILD_AGENT_CREDENTIALS | Out-File UpdateUE4\service-account-credentials.json -Encoding ASCII
        env:
          GCP_GAME_BUILD_AGENT_CREDENTIALS: ${{ secrets.GCP_GAME_BUILD_AGENT_CREDENTIALS }}

      - name: Update UE4
        run: .\UpdateUE4\UpdateUE4.ps1

      - name: Build game (Win64)
        run: .\BuildGame.bat

      - name: Setup credentials for cloud storage
        run: $env:GCP_GAME_BUILD_AGENT_CREDENTIALS | Out-File UploadGame\service-account-credentials.json -Encoding ASCII
        env:
          GCP_GAME_BUILD_AGENT_CREDENTIALS: ${{ secrets.GCP_GAME_BUILD_AGENT_CREDENTIALS }}

      - name: Upload game as game-${{ github.sha }}-win64
        run: .\UploadGame\UploadGame.ps1 game-${{ github.sha }}-win64

  stop-agents:
    needs: [ build-win64 ]
    name: "Stop build agents"
    runs-on: ubuntu-latest
    steps:
      - run: curl ${{ secrets.WATCHDOG_TRIGGER_URL }}
